(function() {var implementors = {};
implementors["cast"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cast/enum.Error.html\" title=\"enum cast::Error\">Error</a>",];
implementors["cortex_m"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/exception/enum.Exception.html\" title=\"enum cortex_m::exception::Exception\">Exception</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/control/enum.Npriv.html\" title=\"enum cortex_m::register::control::Npriv\">Npriv</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/control/enum.Spsel.html\" title=\"enum cortex_m::register::control::Spsel\">Spsel</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/control/enum.Fpca.html\" title=\"enum cortex_m::register::control::Fpca\">Fpca</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/faultmask/enum.Faultmask.html\" title=\"enum cortex_m::register::faultmask::Faultmask\">Faultmask</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/primask/enum.Primask.html\" title=\"enum cortex_m::register::primask::Primask\">Primask</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/enum.Reserved.html\" title=\"enum cortex_m::Reserved\">Reserved</a>",];
implementors["stm32f100xx"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/primask/enum.Primask.html\" title=\"enum cortex_m::register::primask::Primask\">Primask</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/control/enum.Fpca.html\" title=\"enum cortex_m::register::control::Fpca\">Fpca</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/exception/enum.Exception.html\" title=\"enum cortex_m::exception::Exception\">Exception</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/control/enum.Spsel.html\" title=\"enum cortex_m::register::control::Spsel\">Spsel</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/control/enum.Npriv.html\" title=\"enum cortex_m::register::control::Npriv\">Npriv</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/register/faultmask/enum.Faultmask.html\" title=\"enum cortex_m::register::faultmask::Faultmask\">Faultmask</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"cortex_m/enum.Reserved.html\" title=\"enum cortex_m::Reserved\">Reserved</a>",];
implementors["vl"] = ["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"vl/serial/struct.Serial.html\" title=\"struct vl::serial::Serial\">Serial</a>&lt;'a&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"vl/timer/struct.Timer.html\" title=\"struct vl::timer::Timer\">Timer</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
